spring:
  application:
    name: remote-print-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/remote_print}
    username: ${DB_USERNAME:andrey}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

printer:
  name: Canon LBP2900

document:
  max-size-bytes: 20971520
  libreoffice-path: ${LIBREOFFICE_PATH:/Applications/LibreOffice.app/Contents/MacOS/soffice}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
  allowed-chat-ids: ${TELEGRAM_ALLOWED_CHAT_IDS:}